### ISSUE TITLE
TrackJs seems to override window.onerror if already set

### ISSUE THREAD

**Issue by slorber** [TrackJs/trackjs-package#4] opened 2015-02-20 15:56 UTC
I'm testing TrackJS and Errorception to see which fit best my needs.

Here's my integration:

``` javascript
        <!-- Errorception -->
        <script crossorigin>
        (function(_,e,rr,s){_errs=[s];var c=_.onerror;_.onerror=function(){var a=arguments;_errs.push(a);
        c&&c.apply(this,a)};var b=function(){var c=e.createElement(rr),b=e.getElementsByTagName(rr)[0];
        c.src="//beacon.errorception.com/"+s+".js";c.async=!0;b.parentNode.insertBefore(c,b)};
        _.addEventListener?_.addEventListener("load",b,!1):_.attachEvent("onload",b)})
        (window,document,"script","token");
        </script>

        <!-- TrackJs -->
        <script type="text/javascript">window._trackJs = { token: 'token' };</script>
        <script type="text/javascript" src="//d2zah9y47r7bi2.cloudfront.net/releases/current/tracker.js" crossorigin></script>
```

It seems TrackJS overrides Errorception listener because only TrackJS receive the errors

---

``` javascript
        <!-- TrackJs -->
        <script type="text/javascript">window._trackJs = { token: 'token' };</script>
        <script type="text/javascript" src="//d2zah9y47r7bi2.cloudfront.net/releases/current/tracker.js" crossorigin></script>

        <!-- Errorception -->
        <script crossorigin>
        (function(_,e,rr,s){_errs=[s];var c=_.onerror;_.onerror=function(){var a=arguments;_errs.push(a);
        c&&c.apply(this,a)};var b=function(){var c=e.createElement(rr),b=e.getElementsByTagName(rr)[0];
        c.src="//beacon.errorception.com/"+s+".js";c.async=!0;b.parentNode.insertBefore(c,b)};
        _.addEventListener?_.addEventListener("load",b,!1):_.attachEvent("onload",b)})
        (window,document,"script","token");
        </script>
```

By registering Errorception after TrackJS it works better because Errorception does not override onerror set by Trackjs but simply proxy it.

**Comment by slorber** [comment] 2015-02-20 16:18
see https://errorception.com/docs/onerror

**Comment by toddhgardner** [comment] 2015-02-20 16:19
Thanks @slorber, you're right we should proxy it. I'll try to get this in place for our next tracker release.

**Comment by toddhgardner** [comment] 2016-08-11 18:38
Fixed in 2.5.0

**Comment by abhilashlr** [comment] 2016-08-22 10:58
Hello @toddhgardner,

When I try to incorporate window.onerror = function(error) {} in my code, error is being received as the window object while the original error is being captured in trackJS. This seems to happen after 2.5.0, tested with 2.4.0 and it seems to work fine.

Looks like this is due to a method watchWindowErrors where there is a **d.apply(a,c)** where a is the window object and **c** is the array containing the window object. Shouldn't it send the window.onerror's default params instead, like this => **d.apply(a, [e, f, g, h, k])**, so that any other window.onerror watches still work with trackJS included?

Would be great if you can provide some insights.

Thanks

**Comment by toddhgardner** [comment] 2016-08-22 15:16
hi @abhilashlr, thanks for letting us know. Will check this out and let you know shortly.

**Comment by toddhgardner** [comment] 2016-08-22 15:25
@abhilashlr confirmed. patch coming soon.

**Comment by abhilashlr** [comment] 2016-08-22 17:25
Thank you @toddhgardner

**Comment by toddhgardner** [comment] 2016-08-22 18:44
Hi @abhilashlr this has been patched in 2.5.1

**Closed as completed by toddhgardner** 2016-08-22 18:44 UTC

**Comment by abhilashlr** [comment] 2016-08-23 04:09
Thanks @toddhgardner, will test and confirm.
